title: Dalia Katan | Founder, Strategist, Speaker
description: 'Hi ğŸ‘‹ Iâ€™m Dalia, founder of Presently ğŸ I'm insanely passionate about community, curiosity, and connection.'
author: 'Dalia Katan'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:


plugins:
  - jekyll-redirect-from

plugins:
  - jekyll-sitemap